 apiVersion: argocdproj.io/v1alpha1
 kind: Application
 metadata:
  name: hello-world
  namespace: argocd
 espec:
  project: default

  source:
    repoURL: https://github.com/Thiago-Sorrilha/k8s_hello_world_cka.git
    targetRevision: HEAD
    path: Prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true # mantem o que esta no repo. subscreve qualquer alteracao
      prone: true